/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Donte_Loves_Art (https://sketchfab.com/Donte_Loves_Art)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/happy-new-year-girl-331a66faec5f44bd9c38ef1fff697572
Title: Happy New Year Girl
*/

import React, {useEffect, useRef} from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import {MeshStandardMaterial} from "three";
import useStore from "../../store/store";

export function SecondGirl(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("/secondGirl.gltf");
    const { actions } = useAnimations(animations, group);
    const { secondGirlColors } = useStore();

    const hairMaterial = secondGirlColors.hair!=null?new MeshStandardMaterial({ color: secondGirlColors.hair }):materials.hair
    const suitMaterial =secondGirlColors.suit!=null? new MeshStandardMaterial({ color: secondGirlColors.suit }):materials.bunny_outfit
    const pantsMaterial = secondGirlColors.pants!=null?new MeshStandardMaterial({ color: secondGirlColors.pants }):materials.bunny_outfit
    useEffect(() => {
        Object.values(actions)[0].play()

    });
    return (
        <group ref={group} {...props} dispose={null}  position={[0, -1.6, 0]}>
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model"
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={1.643}
                >
                    <group
                        name="a365deb5a31e48fabd53deca97cef667fbx"
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}
                    >
                        <group name="Object_2">
                            <group name="RootNode">
                                <group
                                    name="Armature"
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={100}
                                >
                                    <group name="Object_5">
                                        <primitive object={nodes._rootJoint} />
                                        <skinnedMesh
                                            name="Object_82"
                                            geometry={nodes.Object_82.geometry}
                                            material={suitMaterial}
                                            skeleton={nodes.Object_82.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_84"
                                            geometry={nodes.Object_84.geometry}
                                            material={hairMaterial}
                                            skeleton={nodes.Object_84.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_86"
                                            geometry={nodes.Object_86.geometry}
                                            material={materials.skin}
                                            skeleton={nodes.Object_86.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_87"
                                            geometry={nodes.Object_87.geometry}
                                            material={materials.nails}
                                            skeleton={nodes.Object_87.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_89"
                                            geometry={nodes.Object_89.geometry}
                                            material={materials.eyes}
                                            skeleton={nodes.Object_89.skeleton}
                                        />
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/secondGirl.gltf");

